
name: Download

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3

      - name: Publish package
        run: mvn install:install-file \
          -Dfile= teste/.m2 \
          -DgroupId=com.demo \
          -DartifactId=demo \
          -Dversion=1.0-snapshot \
          -Dpackaging=jar \
          -DgeneratePom=true

