# This is a basic workflow to help you get started with Actions

name: Primeira pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  create:
    branches: [ main ]
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ "$(git ls-remote --heads https://github.com/renato-r-cardoso-alb/rep.git enh-8 | wc -l)" == 1 }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: variable
        run: echo "res=$(git ls-remote --heads https://github.com/renato-r-cardoso-alb/rep.git enh-8 | wc -l)" >> $GITHUB_ENV
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Compile
        if:  ${{ env.res == 0 }}
        run: mvn package --file "demo/pom.xml"
      
      - name: Verify
        run: mvn verify --file "demo/pom.xml"
        
