# This is a basic workflow to help you get started with Actions

name: Primeira pipeline

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
    paths-ignore: 
      - repVer.json
jobs:
  reset_patch_candidate:
    name: Reset Patch and Candidate Variables
    runs-on: ubuntu-latest
    #if: ${{ (github.event_name == 'create' && startsWith(github.ref_name, 'v')) }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Update JSON patch
        run: echo cheguei1
      - name: Define Variables # "name": optional, the name of the step
        run: "echo IP=${curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//'}" >> GITHUB_ENV

      - name: Test
        run: | 
          echo ${{ env.IP }}
          mvn test --file "demo/pom.xml"

