# This is a basic workflow to help you get started with Actions

name: Primeira pipeline

# Controls when the workflow will run
on:
  push:
    branches: [ v* ]
    paths-ignore: 
      - repVer.json
  create:
    branches: [ v* ]
    paths-ignore: 
      - repVer.json

jobs:
  reset_patch_candidate:
    name: Reset Patch and Candidate Variables
    runs-on: ubuntu-latest
    #if: ${{ (github.event_name == 'create' && startsWith(github.ref_name, 'v')) }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Update JSON patch
        run: echo cheguei1

  candidate_pipe:
    name: Candidate Pipeline
    runs-on: ubuntu-latest
    needs: reset_patch_candidate
    #if: success() || (needs.reset_patch_candidate.result == 'skipped') &&  ${{ startsWith(github.ref_name, 'v') }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
  
      - name: set variables
        run: echo  "`jq '.repName |= .+ ["SBI":"v3.0"]' repVer.json`" > repVer.json
        
      - name: Create commit for updated repositoriesDispach
        uses: test-room-7/action-update-file@v1
        with:
            file-path: repVer.json
            commit-msg: Update version file
