# This is a basic workflow to help you get started with Actions

name: Primeira pipeline

# Controls when the workflow will r

on:
  push:
    branches: [ v* ]
    paths-ignore: 
      - repVer.json
  create:
    branches: [ v* ]
    paths-ignore: 
      - repVer.json
env: # 'env': optional, defines varibles of the workflow
  SKIP: needs.reset_patch_candidate.result == 'skipped'
  
jobs:
  reset_patch_candidate:
    name: Reset Patch and Candidate Variables
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'create' && startsWith(github.ref_name, 'v')) }} 
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Update JSON patch
        run: echo cheguei1


  candidate_pipe:
    name: Candidate Pipeline
    runs-on: ubuntu-latest
    needs: reset_patch_candidate
    if: success() || ${{ env.SKIP && startsWith(github.ref_name, 'v') }} 
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
  
      - name: set variables
        run: echo cheguei
        
