# This is a basic workflow to help you get started with Actions

name: Primeira pipeline

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
    paths-ignore: 
      - repVer.json
jobs:
  reset_patch_candidate:
    name: Reset Patch and Candidate Variables
    runs-on: ubuntu-latest
    #if: ${{ (github.event_name == 'create' && startsWith(github.ref_name, 'v')) }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Update JSON patch
        run: echo cheguei1
        
      - name: set var
        run: |
          echo "REP=$(jq '.repVer.SBI | contains( "v2.0" )' repVer.json )" >> $GITHUB_ENV
          echo "REP1=$(jq -r '.repVer.SBI' repVer.json)" >> $GITHUB_ENV
          echo "REP2=$(jq '.repVer | contains( "SBI" )' repVer.json )" >> $GITHUB_ENV

      - name: Test
        run: | 
          echo ${{ env.REP }}
          echo ${{ env.REP1 }}
          echo ${{ env.REP2 }}

