# This is a basic workflow to help you get started with Actions

name: Minikube Deployment

on:
  push:
    branches: [ enh-*, bug-*]



jobs:

##################################################################################################################

  dev_pipe_test:
    name: SBI Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: set variables for enh
        if: ${{ startsWith(github.ref_name, 'enh')) }}
        run: |
          echo "REVISION=$(date '+%Y%m%d%H%M')" >> $GITHUB_ENV
          echo "TESTFILE=${GITHUB_REF_NAME##*enh-}Test" >> $GITHUB_ENV

      - name: set variables for bug
        if: ${{ startsWith(github.ref_name, 'bug')) }}
        run: |
          echo "REVISION=$(date '+%Y%m%d%H%M')" >> $GITHUB_ENV
          echo "TESTFILE=${GITHUB_REF_NAME##*bug-}Test" >> $GITHUB_ENV
          
      - name: echo
        run: echo ${{ env.TESTFILE }}
