---
 apiVersion: v1
 kind: Pod
 metadata:
   name: test
   labels:
     app: web
 spec:
   containers:
     - name: rss-reader
       image: ghcr.io/renato-r-cardoso-alb/img:teste
       ports:
         - containerPort: 8500